version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - test

  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - test

  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    environment:
      PORT: 4200
      # PROXY_API: http://backend:8000/
    ports:
      - 4200:4200
    networks:
      - test

networks:
  test: