version: '3'

services:
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    volumes:
        - ./db_data:/var/lib/postgresql/data
    ports:
        - 5432:5432
    networks:
        - finmapp

  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: 'tomato@finmapp.com'
        PGADMIN_DEFAULT_PASSWORD: 'tomato'
    ports:
        - 16543:80
    networks:
        - finmapp

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app  # Mount backend source code
      - ./backend_data:/var/lib/backend_data  # Example additional volume for backend data
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - finmapp

  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    environment:
      PORT: 4200
      PROXY_API: http://backend:8000/
    volumes:
      - ./frontend:/usr/src/app  # Mount frontend source code
      - ./frontend_data:/var/lib/frontend_data  # Example additional volume for frontend data
    ports:
      - 4200:4200
    networks:
      - finmapp


volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data

networks:
  finmapp:
